//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;

    public partial class Client
    {
        public int ClientID { get; set; }
        public string Status { get; set; }
        public string Name { get; set; }
        public string LastName { get; set; }
        public Nullable<float> Deposit { get; set; }
        public Nullable<float> Percent { get; set; }
        public Nullable<float> Accummulation { get; set; }
        public Nullable<float> Balance { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public Nullable<System.DateTime> DateOfDeposit { get; set; }

        public override string ToString()
        {
            return $"{ClientID,5} |" +
                   $"{Status,10} |" +
                   $"{Name,10} |" +
                   $"{LastName,10} |" +
                   $"{Deposit,10} |" +
                   $"{Percent,5} |" +
                   $"{Accummulation,10} |" +
                   $"{Balance,10} |" +
                   $"{DateOfDeposit,10} |";
        }
    }
}
